#! /usr/bin/perl

=head1 NAME

http_mping - Munin plugin to monitor HTTP request responce time

=head1 CONFIGURATION

The following configuration variables are used

 targets - array of targets in "name=http://target/" connected with ","

=head1 LICENSE

MPL/GPL

=cut

use strict;
use LWP::UserAgent;
use LWP::Protocol::https;
use Time::HiRes qw( gettimeofday tv_interval );

my $cmd_wget = '/usr/bin/wget';
my ($env_targets, $env_repeat);
if (defined($ENV{targets})) {$env_targets = $ENV{targets}; }
else {$env_targets = 'localhost=http://localhost/'; }
if (defined($ENV{repeat})) {$env_repeat = $ENV{repeat}; }
else {$env_repeat = 1; }
my @cnf_targets = split(/,/, $env_targets);
my ($cid, $cname, $curl);

if (defined $ARGV[0] and $ARGV[0] eq 'autoconf') {
    if (! -f $cmd_wget) {
        print "no (need wget command)\n";
        exit 0;
    }
    print "yes\n";
    exit 0;
}

if (defined $ARGV[0] and $ARGV[0] eq "config")
{
    print "graph_title HTTP loadtime\n";
    print "graph_category network\n";
    print "graph_vlabel Load time in seconds\n";
    print "graph_info Load time for specified URLs\n";
	print "graph_args --base 1000 -l 0\n";

    foreach (0 ... $#cnf_targets) {
        $cid = $_;
        $cname = substr($cnf_targets[$cid], 0, index($cnf_targets[$cid], '='));
        $curl = substr($cnf_targets[$cid], length($cname) + 1);
        print "p$cid.label $cname\n";
        print "p$cid.info $curl\n";
    }
    exit 0;
}

my $ua = LWP::UserAgent->new;
my ($ts, $tv, $ua_out, @times);

foreach (0 ... $env_repeat) {
foreach (0 ... $#cnf_targets) {
    $cid = $_;
    $cname = substr($cnf_targets[$cid], 0, index($cnf_targets[$cid], '='));
    $curl = substr($cnf_targets[$cid], length($cname) + 1);
    $ts = [gettimeofday];
    $ua_out = $ua->get($curl);
    $tv = tv_interval($ts);
    if (! $ua_out->is_success) {$tv = 0; }
    $times[$cid] = $times[$cid] + $tv;
}
}
foreach (0 ... $#cnf_targets) {
    print "p$_.value " . $times[$_] / $env_repeat . "\n";
}

exit;

