#!/usr/bin/perl -w
# -*- perl -*-

=head1 NAME

snmp__cisco_memory - Munin plugin to monitor memory usage of cisco switch

=head1 CONFIGURATION

The following configuration variables are used

 host      - SNMP host to contact (default taken from link name)
 port      - SNMP port to use (default 161)
 community - SNMP community string to use (default "public")

=head1 LICENSE

MPL/GPL

=cut

use strict;
use Munin::Plugin::SNMP;

use Data::Dumper;

# oid
my $oidBase  = '1.3.6.1.4.1.9.9.48.1.1.1';
my $memtype = {
    1 => 'processor',
    2 => 'io',
    3 => 'pci',
    4 => 'fast',
    5 => 'multibus',
};

if (defined $ARGV[0] and $ARGV[0] eq "snmpconf")
{
    print "require $oidBase [1-6]\n";
    exit 0;
}

my $session = Munin::Plugin::SNMP->session();
my (%info, $cid);
my $oidCols = {
                1 => 'type',
                2 => 'name',
                3 => 'alt',
                4 => 'valid',
                5 => 'used',
                6 => 'free',
};

if (defined $ARGV[0] and $ARGV[0] eq "config")
{
    my ($host) = Munin::Plugin::SNMP->config_session();
    print "host_name $host\n";
    print "graph_title Cisco memory\n";
    print "graph_category system\n";
    print "graph_vlabel Byte\n";
    print "graph_info Memory usage\n";
	print "graph_args --base 1000 -l 0\n";

    if (&get_multi_composite($session, $oidBase, $oidCols, \%info) != 0) {
        foreach (keys %info) {
            print "i${_}_Used.label " . $info{$_}->{name} . " Used\n";
            print "i${_}_Used.type GAUGE\n";
            print "i${_}_Free.label " . $info{$_}->{name} . " Free\n";
            print "i${_}_Free.type GAUGE\n";
        }
    }
    exit 0;
}

if (&get_multi_composite($session, $oidBase, $oidCols, \%info) != 0) {
    foreach (keys %info) {
        print "i${_}_Used.value $info{$_}->{used}\n";
        print "i${_}_Free.value $info{$_}->{free}\n";
    }
}


exit;

sub get_multi_composite {
    my ($session, $oidBase, $oidCols, $snmpinfo) = @_;
    my $ret = $session->get_hash(
            -baseoid => $oidBase,
            -cols    => $oidCols);
    if (! defined($ret)) {return 0; }
    my ($ckey, $corig);
    foreach $corig (keys %$ret) {
        $corig =~ /(\d+)/;
        $ckey = $1;
        if (! defined($snmpinfo->{$ckey})) {$snmpinfo->{$ckey} = {}; }
        foreach (keys %{$ret->{$corig}}) {
            $snmpinfo->{$ckey}->{$_} = $ret->{$corig}->{$_};
        }
    }
    return 1;
}


sub get_numeric {
    my ($val) = @_;
    if ($val =~ /^([0-9\.]+)/) {return $1; }
    return undef;
}

sub get_single {
    my ($session, $oid) = @_;
    my $res = $session->get_request($oid);
    my $val = undef;
    if ($session->error_status) {return undef; }
    # treat only if value returned, unless not touch $val
    if (defined($res->{$oid})) {
        if ($res->{$oid} ne 'noSuchObject') {$val = $res->{$oid}; }
    } elsif (defined($res->{$oid . '.0'})) {
        if ($res->{$oid . '.0'} ne 'noSuchObject') {$val = $res->{$oid . '.0'}; }
    } else {
    }
    return $val;
}

