#!/usr/bin/perl -w
# -*- perl -*-

=head1 NAME

snmp__atenpdu_sensor - Munin plugin to monitor sensor values of ATEN PN* PDU

=head1 CONFIGURATION

The following configuration variables are used

 host      - SNMP host to contact (default taken from link name)
 port      - SNMP port to use (default 161)
 community - SNMP community string to use (default "public")

=head1 LICENSE

MPL/GPL

=cut

use strict;
use Munin::Plugin::SNMP;

# oid
my $oidPart  = '1.3.6.1.4.1.21317.1.3.2.30.2.1.1.0';
my $oidSensor = '1.3.6.1.4.1.21317.1.3.2.30.2.1.4.1.';

if (defined $ARGV[0] and $ARGV[0] eq "snmpconf")
{
    print "require $oidPart\n";
    print "require $oidSensor [1-8]\n";
    exit 0;
}

my $session = Munin::Plugin::SNMP->session();
my $partid = $session->get_single($oidPart);
my ($cid, $cval, @carr);

if (defined $ARGV[0] and $ARGV[0] eq "config")
{
    my ($host) = Munin::Plugin::SNMP->config_session();
    print "host_name $host\n";
    print "graph_title PDU $partid sensor\n";
    print "graph_category system\n";
    print "graph_vlabel Value\n";
    print "graph_info Sensor read\n";
	print "graph_args --base 1000 -l 0\n";

    foreach (2 ... 8) {
        $cid = $_;
        if (defined($cval = &get_single($session, $oidSensor . $_ . '.1'))) { 
            @carr = split(/\//, $cval);
            foreach (0 ... $#carr) {
                $carr[$_] =~ /^ ?([0-9\.]+)([^0-9]*) ?/;
                print "s$cid" . "p$_.label Port $cid Sensor $_ [$2]\n";
            }
        }
    }
   
    exit 0;
}

my $oval;

foreach (2 ... 8) {
    $cid = $_;
    if (defined($oval = &get_single($session, $oidSensor . $_ . '.1'))) {
        @carr = split(/\//, $oval);
        foreach (0 ... $#carr) {
                $carr[$_] =~ /^ ?([0-9\.]+)([^0-9]*) ?/;
                print "s$cid" . "p$_.value $1\n";
        }
    }
}


sub get_numeric {
    my ($val) = @_;
    if ($val =~ /^([0-9\.]+)/) {return $1; }
    return undef;
}

sub get_single {
    my ($session, $oid) = @_;
    my $res = $session->get_request($oid);
    my $val = undef;
    if ($session->error_status) {return undef; }
    # treat only if value returned, unless not touch $val
    if (defined($res->{$oid})) {
        if ($res->{$oid} ne 'noSuchObject') {$val = $res->{$oid}; }
    } elsif (defined($res->{$oid . '.0'})) {
        if ($res->{$oid . '.0'} ne 'noSuchObject') {$val = $res->{$oid . '.0'}; }
    } else {
    }
    return $val;
}

